FROM node:18-alpine

# Install dependencies for development
RUN apk add --no-cache libc6-compat curl

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
  elif [ -f package-lock.json ]; then npm ci; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Copy source code
COPY . .

EXPOSE 3000

# Run the development server
CMD \
  if [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm dev; \
  elif [ -f package-lock.json ]; then npm run dev; \
  else echo "Lockfile not found." && exit 1; \
  fi
